from .test_chamfer import *
from .test_classes import *
from .test_conversion import *
from .test_neighbours import *
from .test_nricp import *
from .test_plot import *
from .test_pretreat import *
from .test_rotation_translate import *
from .test_solver import *